conflicts

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,9 +1,24 @@
 #!/bin/bash
 # bin/compile <build-dir> <cache-dir> <env-dir>
 
-echo "we will compile things"
+# Fail immediately on non-zero exit code.
+set -e
+# Fail immediately on non-zero exit code within a pipeline.
+set -o pipefail
+# Fail on undeclared variables.
+set -u
+# Debug, echo every command
+#set -x
 
-BUILD_DIR=$1/frontend
+function indent() {
+  c='s/^/       /'
+  case $(uname) in
+    Darwin) sed -l "$c";;
+    *)      sed -u "$c";;
+  esac
+}
+
+BUILD_DIR=$1
 CACHE_DIR=$2
 ENV_DIR=$3
 BP_DIR=`cd $(dirname $0); cd ..; pwd`
@@ -13,5 +28,40 @@ echo "BP_DIR is: $BP_DIR"
 # Switch to new Node auto build behavior ahead of release
 export NEW_BUILD_SCRIPT_BEHAVIOR=true
 
-echo "runing npm install --prefix frontend"
-monitor "npm-install" npm install --prefix frontend --production="$production" --unsafe-perm --userconfig "$build_dir/.npmrc" 2>&1
+# Use architecture of multi-buildpack to compose behavior.
+# https://github.com/heroku/heroku-buildpack-multi
+cp $BP_DIR/.buildpacks $BUILD_DIR/.buildpacks
+url=https://github.com/heroku/heroku-buildpack-multi.git
+branch=""
+dir=$(mktemp -t buildpackXXXXX)
+rm -rf $dir
+
+echo "=====> Downloading Buildpack: $url"
+
+if [[ "$url" =~ \.tgz$ ]] || [[ "$url" =~ \.tgz\? ]]; then
+  mkdir -p "$dir"
+  curl -s "$url" | tar xvz -C "$dir" >/dev/null 2>&1
+else
+  git clone $url $dir >/dev/null 2>&1
+fi
+cd $dir
+
+if [ "$branch" != "" ]; then
+  git checkout $branch >/dev/null 2>&1
+fi
+
+chmod -f +x $dir/bin/{detect,compile,release}
+
+framework=$($dir/bin/detect $1/frontend)
+
+if [ $? == 0 ]; then
+  echo "=====> Detected Framework: $framework"
+  $dir/bin/compile $BUILD_DIR $CACHE_DIR $ENV_DIR
+
+  if [ $? != 0 ]; then
+    exit 1
+  fi
+else
+  echo "create-react-app `.buildpacks` not defined. Exiting."
+  exit 1
+fi
